name: esl
version: 0.0.21
author: Kim Rostgaard Christensen <krc@retrospekt.dk>
description: A FreeSWITCH event socket library for Dart.
homepage: https://github.com/rostgaard/libesl-dart

dependencies:
  logging: '>=0.9.2 < 1.0.0'

dev_dependencies:
  test: any
