name: esl
version: 0.0.15-beta
author: Kim Rostgaard Christensen <krc@retrospekt.dk>
description: A FreeSWITCH event socket library for Dart.
homepage: https://github.com/rostgaard/libesl-dart
dev_dependencies:
  junitconfiguration: '>=1.1.1 < 2.0.0'
  logging: '>=0.9.2 < 1.0.0'
  unittest: '>=0.10.0 < 1.0.0'
