name: esl
version: 0.1.0
author: Kim Rostgaard Schomacker <krc@retrospekt.dk>
description: A FreeSWITCH event socket library for Dart.
homepage: https://github.com/rostgaard/libesl-dart

environment:
  sdk: '>=2.0.0 <3.0.0'
  
dependencies:
  logging: '>=0.11.3 < 1.0.0'

dev_dependencies:
  test: any
